### ISSUE TITLE
Problem with copy and replace

### ISSUE THREAD

**Issue by dr-costas** [MorenoLaQuatra/audioset-download#1]
Hi, 

When using copy and replace it seems that files are not copied.

**Comment by dr-costas** [comment]
Yes, it seems that FFMPEG deletes the original file and the copy process cannot find the file to copy it.

**Comment by dr-costas** [comment]
Actually, not. There is a logical error at your code. Line 124, of Downloader.py, the handling of the source and destination paths is wrong.

**Comment by MorenoLaQuatra** [comment]
Merged in the main code now, thanks to #2
